  CREATE TABLE "STAGE_2_ARCHIVE" 
   ("STAGE_2_ID" NUMBER,
    "CLAIM_ID" NUMBER,
   "CLAIM_TYPE" VARCHAR2(20 BYTE),  
	"CLAIM_DATE" DATE, 
	"CLAIM_AMOUNT" NUMBER, 
	"MEMBER_ID" VARCHAR2(20 BYTE)
   ) ;